name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: The semver to use
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
  pull_request:
    types: [closed]

jobs:
  release:
    permissions:
      pull-requests: write
      contents: write
#     `id-token: write` is required by NPM provenance  
      id-token: write
    runs-on: ubuntu-latest
    steps:
#     Explicitly set NPM version
      - run: "npm i -g npm@9.4.0"
      - run: "npm -v"
#     SHA of latest commit in feat/provenance branch
      - uses: AlanSl/optic-release-automation-action@d87689b7de8e3be55c4e41d4ad8e240190a9392c
        with:
          semver: ${{ github.event.inputs.semver }}
          commit-message: 'chore: release {version}'
          npm-token: ${{ secrets[format('NPM_TOKEN_{0}', github.actor)] || secrets.NPM_TOKEN }}
          optic-token: ${{ secrets[format('OPTIC_TOKEN_{0}', github.actor)] || secrets.OPTIC_TOKEN }}
          build-command: npm ci
#          provenance: true
