name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: The semver to use
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
  pull_request:
    types: [closed]

jobs:
  release:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
#     SHA of latest commit in feat/provenance branch
      - uses: AlanSl/optic-release-automation-action@89ab69680620f934306b04472642bd4078f7ab6c
        with:
          semver: ${{ github.event.inputs.semver }}
          commit-message: 'chore: release {version}'
          npm-token: ${{ secrets[format('NPM_TOKEN_{0}', github.actor)] || secrets.NPM_TOKEN }}
          optic-token: ${{ secrets[format('OPTIC_TOKEN_{0}', github.actor)] || secrets.OPTIC_TOKEN }}
          build-command: npm ci
          provenance: true

